#include"motors.h"
#include"uart.h"
#include<avr/io.h>
#include<string.h>
#include<stdio.h>
#include<stdlib.h>

uint16_t PWM1 = 1999;
uint16_t PWM2 = 1999;

void motorsInit(void)
{
	/* initialization pins for motors */
	DDRB |= 0x66;
	/* set a direction */
	PORTB |= 0x06; // direction forward

}
/*
 * Motor drivers
Two on-board Texas Instruments DRV8838 motor drivers power the Balboa’s two micro metal gearmotors. Four Arduino pins are used to control the drivers:

Digital pin 15, or PB1, controls the right motor direction (LOW drives the motor forward, HIGH drives it in reverse).
Digital pin 16, or PB2, controls the left motor direction.
Digital pin 9, or PB5, controls the right motor speed with PWM (pulse width modulation) generated by the ATmega32U4’s Timer1.
Digital pin 10, or PB6, controls the left motor speed with PWM.
 *
 */
void SetSpeed(int16_t LPWM1, int16_t RPWM2)
{
	/*send PWM to PC (UART)*/
//		uartSendMsg("\n");
//		uartSendNr(LPWM1);
//		uartSendMsg("\t");
//		uartSendNr(RPWM2);

	/*LPWM1 & RPWM2 [-100 ; +100]*/

	/*set dierection motor*/
	/*Left motor*/
	if((LPWM1 >= 0) && (LPWM1 < 100))
		PORTB |= 0b00000100;	//0b11111011			//Left forward
	else												//or
		PORTB &= 0b11111011;							//Left back

	/*Right motor*/
	if((RPWM2 >= 0) && (RPWM2 < 100))
		PORTB &= 0b11111101;	 //PORTB |= 0b00000010;	//0b11111101			//Right forward
	else			//or
		PORTB |= 0b00000010;		//PORTB &= 0b11111101; 							//Right Back


	LPWM1 = 2000 + (-20*abs(LPWM1)) - 1;
	RPWM2 = 2000 + (-20*abs(RPWM2)) - 1;
	/*LPWM max = (2000-1500-1) //PWM min = (2000-0-1)*/

	if((LPWM1<=1999 && LPWM1>10) && (RPWM2<=1999 && RPWM2>10))
	{
		PWM1 = LPWM1;
		PWM2 = RPWM2;
	}
}

//void SetDirection(int16_t LPWM1, int16_t RPWM2)
//{
//	/*set dierection motor*/
//
//	/*Left motor*/
//	if((LPWM1 >= 0) && (LPWM1 < 100))
//		PORTB |= 0b00000100;	//0b11111011			//Left forward
//	else												//or
//		PORTB &= 0b11111011;							//Left back
//
//	/*Right motor*/
//	if((RPWM2 >= 0) && (RPWM2 < 100))
//		PORTB |= 0b00000010;	//0b11111101			//Right forward
//	else												//or
//		PORTB &= 0b11111101; 							//Right Back
//}





